name = "umesh-malik"
compatibility_date = "2024-01-01"
main = "worker/index.ts"

[assets]
directory = "./build"

[[d1_databases]]
binding = "DB"
database_name = "analytics"
database_id = "36747131-23c3-43fe-ba4c-bf8821c7f0b5"

[triggers]
crons = ["0 */6 * * *"]
